import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

import { mono16BitPCMData } from "../../src/core/wavFileWriter.js";

const samples = new Int16Array([0, 1, -1, 32_767, -32_768, 4_660, -4_660]);

describe("WAVFileWriter", () => {
  it("matches the fixture generated by the Swift WAVFileWriter", async () => {
    const expected = await readFile(
      new URL("../fixtures/known-good-mono.wav", import.meta.url),
    );
    const actual = mono16BitPCMData(samples, 16_000);

    expect(Buffer.from(actual)).toEqual(expected);
  });

  it("writes the mono PCM header and signed samples byte-for-byte", () => {
    const data = mono16BitPCMData(samples, 16_000);
    const view = new DataView(data.buffer, data.byteOffset, data.byteLength);

    expect(ascii(data, 0, 4)).toBe("RIFF");
    expect(view.getUint32(4, true)).toBe(36 + samples.byteLength);
    expect(ascii(data, 8, 4)).toBe("WAVE");
    expect(ascii(data, 12, 4)).toBe("fmt ");
    expect(view.getUint16(20, true)).toBe(1);
    expect(view.getUint16(22, true)).toBe(1);
    expect(view.getUint32(24, true)).toBe(16_000);
    expect(view.getUint32(28, true)).toBe(32_000);
    expect(view.getUint16(32, true)).toBe(2);
    expect(view.getUint16(34, true)).toBe(16);
    expect(ascii(data, 36, 4)).toBe("data");
    expect(view.getUint32(40, true)).toBe(samples.byteLength);
    expect(view.getInt16(54, true)).toBe(4_660);
    expect(view.getInt16(56, true)).toBe(-4_660);
  });
});

function ascii(data: Uint8Array, offset: number, length: number): string {
  return String.fromCharCode(...data.subarray(offset, offset + length));
}
